<?php
/**
 * config-local.example.php -- TEMPLATE TO COPY.
 *
 * This file is NOT read: only `config-local.php`, in this same directory, is.
 * Copy this one under that name, then adapt it.
 *
 * It only needs to contain what differs from config.php's defaults -- the other
 * keys keep their default values.
 *
 * YOU PROBABLY DO NOT NEED THIS FILE. `install.php` writes one, having chosen a
 * storage location the web server does not serve and PROVED it by asking for
 * that file's own URL over HTTP. Copy this one by hand when you want something
 * the installer does not ask about -- a relay, several projects, credentials
 * read from outside the web root.
 *
 * TWO FORMS FOR EVERY DATABASE CREDENTIAL
 *
 *   'user' => 'mysite'                        the value in the clear
 *   'user' => array('file' => '/path')        the value READ FROM a file
 *                                             dropped outside the web root
 *
 * The second form is the reason this mechanism exists: many hosts drop the
 * database credentials in a directory next to the web root, out of the
 * browser's reach. We READ them there; we never copy them into a served file.
 * Direct consequence: this file then contains no secret at all, only PATHS to
 * secrets, and it can be versioned without fault.
 *
 * WHAT IS NOT HERE, AND NEVER WILL BE: THE KEY.
 *
 * The 256-bit key does not leave the browser. The server does not receive it
 * at any point, in any form, in any mode. What is written below is the PROJECT
 * id, which descends from it (HKDF) but does not lead back to it -- and which is
 * public anyway: it appears in the tag of every annotated page.
 *
 * KEY LOST = NOTES LOST. There is no recovery, no security question, no escrow
 * third party. This file can do nothing about it.
 *
 * THE PATH MUST BE ANCHORED ON __DIR__
 *
 * PHP resolves a relative path against the process's WORKING DIRECTORY, NOT
 * against the file that writes it -- and that directory is not always the one
 * you think. Writing '../../secrets/password' would therefore produce, one day,
 * an incomprehensible "unreadable file". Always write
 * __DIR__ . '/../../secrets/password', and count the levels: from this file,
 * '..' climbs to the tool's served root, '../..' to the directory where the
 * tool is mounted, and so on. The configuration refuses any path that is not
 * absolute after resolution, showing the one it got.
 *
 * The file names below are EXAMPLES. Every host has its own; it is up to the
 * local file, and it alone, to know them.
 */

if (!defined('AP_INTERNAL')) {
    http_response_code(404);
    exit;
}

return array(

    // Nothing answers until this is true.
    'active' => true,

    // WHERE IS THIS SERVER DROPPED?
    //
    //   'self-hosted' : on the site under review itself, behind the same access
    //                   restriction as it. Plain mode is possible there, the
    //                   Origin header is optional, and the backfill action is
    //                   available.
    //   'relay'       : on a third-party machine serving several sites. Plain
    //                   mode is IMPOSSIBLE there, the Origin header is required
    //                   on writes, and the backfill is refused.
    //
    // There is no third value, and a typo is a failure: falling back in silence
    // on a default would serve plaintext to a third party without anyone
    // noticing.
    'deployment' => 'self-hosted',

    // THE PROJECTS.
    //
    // The key is the project id: 22 characters, generated by the setup screen IN
    // THE BROWSER, from the key. Copy it from that screen; the server does not
    // compute it, it recognises it.
    //
    // When self-hosted there is only one entry. It is the same column and the
    // same query as on a relay: a single tenant is a multi-tenant with one
    // tenant.
    //
    // 'origins': the origins allowed to consume this project. A project may
    // declare several, and that is intended -- a staging site and the production
    // it becomes are the same project, with the same notes. Write them as the
    // browser sends them: scheme://host[:port], with no path and no trailing
    // slash. This is an ANTI-ABUSE measure; it is NOT a protection against XSS,
    // which runs inside the page itself.
    //
    // 'mode': 'encrypted' (default) or 'plain'. Plain mode is only acceptable
    // when self-hosted, where it protects nothing: the notes are in the same
    // database, on the same machine, behind the same access restriction as the
    // site under review. On a relay, declaring it is refused when this file is
    // loaded -- not at the first note.
    'projects' => array(

        '7Qb1kZ3xNvA9dLpEqKf2Zt' => array(
            'origins' => array(
                'https://staging.example.com',
                'https://www.example.com',
            ),
            'mode' => 'encrypted',
        ),

        // A second project, on a relay serving several sites:
        // 'A1b2C3d4E5f6G7h8I9j0Kl' => array(
        //     'origins' => array('https://review.other-example.com'),
        //     'mode'    => 'encrypted',
        // ),
    ),

    // WHICH STORE ANSWERS.
    //
    //   'sqlite'  internal/store-sqlite.php: ONE FILE, nothing to create. This
    //             is the default and what install.php writes. Its only key is
    //             `database.file`, the absolute path of that file;
    //   'mysql'   internal/store.php: a database server and its credentials,
    //             below. The right answer for a busy relay -- SQLite locks the
    //             whole file for each write.
    //
    // Left out entirely, it is deduced: `database.name` set means MySQL, so an
    // installation configured before this key existed keeps its database.
    'storage' => 'mysql',

    // THE SQLITE ROUTE, and it is two lines:
    //
    //   'storage'  => 'sqlite',
    //   'database' => array('file' => '/path/to/somewhere/notes.sqlite'),
    //
    // PUT THAT FILE OUTSIDE THE WEB ROOT. A SQLite file inside it can be
    // FETCHED OVER HTTP; an .htaccess denying it does nothing under nginx, and
    // plenty of cheap hosting is nginx. The store writes an .htaccess and an
    // index.php next to the file wherever it lands, but those are a fallback,
    // not the plan. install.php picks the location and then proves it.

    'database' => array(

        // Host and port: in the clear, they are not secrets.
        'host' => '127.0.0.1',
        'port' => 3306,

        // Form 1 -- credentials read from files dropped outside the web root.
        // Names and levels to adapt to the hosting: count them from THIS file.
        'name'     => array('file' => __DIR__ . '/../../../secrets/database-name'),
        'user'     => array('file' => __DIR__ . '/../../../secrets/database-user'),
        'password' => array('file' => __DIR__ . '/../../../secrets/database-password'),

        // Form 2 -- values in the clear. Only to be used if this file is
        // NEITHER versioned NOR served by the web server.
        // 'name'     => 'my_database',
        // 'user'     => 'my_user',
        // 'password' => 'not to be written here if the file is versioned',
    ),

    // The tables will be called <prefix>notes and <prefix>rate.
    // To be changed if the database is shared.
    'table_prefix' => 'notes_',

    // Input bounds. They size the columns when the table is CREATED: raising
    // them afterwards does not widen an existing table. They apply IN PLAIN
    // MODE ONLY -- in encrypted mode the server sees only an envelope, and does
    // not know where the author ends.
    // 'max_text_length'   => 4000,
    // 'max_author_length' => 80,

    // RATE LIMITING. The values below are the defaults; they suit a review
    // team. On a public relay, lowering them is wiser than raising them. A
    // value of 0 disables the matching counter -- only to be done when
    // self-hosted.
    // 'rate_window_seconds'     => 300,
    // 'rate_writes_per_ip'      => 120,
    // 'rate_writes_per_project' => 300,
    // 'rate_exports_per_ip'     => 20,

    // Maximum number of notes per project; 0 = no limit. Erases nothing and
    // expires nothing: refuses the write beyond, and says so.
    // 'max_notes_per_project' => 5000,

    // THE UPDATE URL, FOR A HOST WITH NEITHER CRON NOR SHELL. Written here,
    // it turns on ?action=update&token=... , which fetches and installs the
    // published version DURING the request and answers with what it did. Put
    // that address in any external scheduler, or open it by hand. Empty, and
    // the action does not exist -- unknown, not refused. 32 characters or more.
    // 'update_token' => 'the 43 characters of anything nobody can guess',

    // WHICH BRANCH THIS SERVER FOLLOWS. `main` is what everybody runs and it
    // is the default, so this line is only needed to leave it. `next` is where
    // a version is validated before users get it: same files, same manifest,
    // every one of them hashed before anything is put in place -- a candidate
    // is verified exactly as a release is. Put it back to `main`, or delete
    // the line, and the next check returns this server to the release.
    //
    // It is also what a fork or a mirror inside a network with no way out to
    // GitHub is pointed at. HTTPS only, and no flag relaxes that.
    // 'update_source' => 'https://raw.githubusercontent.com/tuxo83/annotepage/next/server/webroot/',

    // WHERE A BARE VISIT GOES. Empty: a visit to this directory with no path
    // gets a 404, and api.php is unaffected either way. An absolute http(s)
    // URL sends such a visit there with a 302 -- what a public relay wants, so
    // that somebody landing on the bare host reaches a page explaining what
    // the thing is instead of nothing. It NEVER applies to api.php, to an
    // action, or to the diagnostic.
    // 'forward_root_to' => 'https://annotepage.com',

    // Behind a trusted proxy THAT REWRITES IT ON EVERY REQUEST. With no proxy,
    // leave this key out: a header the client writes itself would make rate
    // limiting bypassable in one line.
    // 'client_ip_header' => 'HTTP_X_FORWARDED_FOR',

    // https IS REQUIRED. Every http request is answered with a 308 towards the
    // same URL over https -- 308 and not 302, so a POST stays a POST and the
    // note keeps its body.
    //
    // Uncomment this ONLY if the redirect loops: that means this host reports
    // an https visitor as http (no HTTPS, no REQUEST_SCHEME, no forwarding
    // header), not that plain http is wanted. ?action=diagnostic prints what
    // the request arrived as. It is a way out, not a preference -- and the
    // widget needs a secure context for WebCrypto, so over http it cannot
    // encrypt anything anyway.
    // 'allow_plain_http' => true,

    // HOW MUCH ?action=diagnostic PUBLISHES, on a page that has no
    // authentication and never had: 'minimal' (the default -- the tool, the
    // version, the format and the verdict), 'full' (everything: the PHP really
    // served, the storage and its engine, this file's path, the update source,
    // the caps, the declared projects), or 'off' (the action is refused like
    // one nobody ever heard of).
    //
    // Set it to 'full' while you diagnose, and set it back. That is what the
    // three values are for.
    // 'diagnostic' => 'full',
);
