<?php
/**
 * origins.php -- THE DOMAIN LOCK, AND NOTHING ELSE.
 *
 * This file holds two things, and they are better off in the same place
 * because the second depends on the first:
 *
 *   1. WHICH PROJECTS EXIST. The configuration declares them by their id (22
 *      base64url characters, derived from the salt IN THE BROWSER: the server
 *      does not compute it, it recognises it).
 *   2. WHICH ORIGINS MAY CONSUME THEM, and the sharing headers that follow.
 *
 * WHAT THIS LOCK IS: an ANTI-ABUSE measure. It stops another site from picking
 * up a project id in the source of a page, writing noise into it and burning
 * the relay's quota.
 *
 * WHAT IT IS NOT, AND IT MUST NEVER BE PRESENTED AS SUCH: a protection against
 * XSS. An XSS runs INSIDE the target page, so with the legitimate origin: it
 * goes through this lock without effort, and it has access to that origin's
 * localStorage anyway, hence to the salt. An XSS on an annotated page
 * compromises the notes of the project, full stop. This file changes nothing
 * about that.
 *
 * WHY SEVERAL ORIGINS PER PROJECT. A staging site and the production it
 * becomes are the same project, with the same notes. That is the operational
 * counterpart of the rule "the domain is not in the key" (FORMAT.md section
 * 1.4): if the domain were part of the secret, the day of the production
 * release would be the day every note became unreadable.
 *
 * THE DOMAIN AND THE PATH PREFIX ARE CONFIGURATION, NOT CRYPTOGRAPHY. The path
 * prefix does not appear here at all, in fact: the server does not see paths in
 * encrypted mode, so prefix scope is checked by the client. It is tidiness, not
 * a security boundary (FORMAT.md section 4).
 */

if (!defined('AP_INTERNAL')) {
    http_response_code(404);
    exit;
}

/**
 * The declared projects, checked and normalised. Computed once.
 *
 * A malformed declaration is a configuration FAILURE, not an ignored project: a
 * project one believes declared and which is not returns "no notes" to a team
 * that wrote thirty, and nobody thinks of rereading the local file.
 *
 * @return array key = id, value = array('origins' => [...], 'mode' => '...')
 */
function ap_declared_projects(array $config)
{
    static $memory = null;
    if ($memory !== null) {
        return $memory;
    }

    $raw = isset($config['projects']) && is_array($config['projects'])
        ? $config['projects'] : array();
    // The result is built in a LOCAL variable and handed to the memo only once
    // complete. Without that, a declaration refused halfway through the array
    // would leave behind a half-made list, which the next call would return
    // without a word -- a declared project would become "unknown" through the
    // sole effect of an error in another one.
    $projects = array();

    foreach ($raw as $id => $declaration) {
        $id = (string) $id;
        if (!ap_is_well_formed_id($id)) {
            throw new ApFailure(
                "Invalid configuration: `" . ap_readable_excerpt($id)
                . "` is not a project id.\n"
                . "An id is exactly 22 characters taken from A-Z a-z 0-9 - _ "
                . "(base64url).\n"
                . "It is generated by the setup screen, in the browser, from the salt. "
                . "The server does not compute it.",
                500);
        }
        if (!is_array($declaration)) {
            throw new ApFailure(
                "Invalid configuration: project " . ap_short_project($id)
                . " must be declared by an array "
                . "array('origins' => array(...), 'mode' => 'encrypted').",
                500);
        }

        // MODE. `encrypted` by default, and that default is not negotiable on a
        // relay: see below.
        $mode = isset($declaration['mode'])
            ? strtolower(trim((string) $declaration['mode'])) : 'encrypted';
        if ($mode !== 'plain' && $mode !== 'encrypted') {
            throw new ApFailure(
                "Invalid configuration: project " . ap_short_project($id)
                . " declares mode `" . ap_readable_excerpt($mode) . "`.\n"
                . "The only two accepted values are `plain` and `encrypted`.",
                500);
        }
        // Encryption is on by default and can only be switched off when
        // self-hosted, where it protects nothing: the notes are in the same
        // database, on the same machine, behind the same access restriction as
        // the site under review. On a relay there is no access restriction to
        // offer -- plain mode there would make somebody else's notes readable by
        // the relay operator and by whoever finds the id. We refuse WHEN
        // READING THE CONFIGURATION, not at write time: an installation that
        // believes itself protected must learn otherwise at the first
        // diagnostic, not at the first note.
        if ($mode === 'plain' && !ap_is_self_hosted($config)) {
            throw new ApFailure(
                "Configuration refused: project " . ap_short_project($id)
                . " declares mode `plain` on a `relay` deployment.\n"
                . "Plain mode is only possible when self-hosted, where the notes sit "
                . "behind the same access restriction as the site under review.\n"
                . "On a relay there is nothing of the sort to offer: the notes would be "
                . "readable by the relay operator and by anyone who finds the project id "
                . "in the source of a page.",
                500);
        }

        // ORIGINS.
        $origins = array();
        $declared = isset($declaration['origins']) ? $declaration['origins'] : array();
        if (is_string($declared)) {
            // A single origin written without an array: it is the most likely
            // typo, and refusing it would teach nobody anything.
            $declared = array($declared);
        }
        if (!is_array($declared) || !$declared) {
            throw new ApFailure(
                "Invalid configuration: project " . ap_short_project($id)
                . " declares no origin.\n"
                . "Example: 'origins' => array('https://staging.example.com', "
                . "'https://www.example.com').\n"
                . "A project with no origin is not `open to everyone`: it is unusable, "
                . "and that is intended.",
                500);
        }
        foreach ($declared as $origin) {
            $normalised = ap_normalise_origin($origin);
            if ($normalised === null) {
                throw new ApFailure(
                    "Invalid configuration: `" . ap_readable_excerpt((string) $origin)
                    . "` is not an origin.\n"
                    . "An origin is written scheme://host[:port], with no path and no "
                    . "trailing slash: https://staging.example.com\n"
                    . "That is exactly what the browser puts in the Origin header; "
                    . "anything else will never match.",
                    500);
            }
            $origins[$normalised] = true;
        }

        $projects[$id] = array(
            'origins' => array_keys($origins),
            'mode'    => $mode,
        );
    }

    $memory = $projects;
    return $memory;
}

/** Shape of a project id: 22 base64url characters. */
function ap_is_well_formed_id($id)
{
    return is_string($id)
        && preg_match('/^[A-Za-z0-9_-]{22}$/', $id) === 1;
}

/**
 * The first six characters of an id, for messages.
 *
 * NEVER the whole id: it is what gives access to the project's rows (FORMAT.md
 * section 6.3), and an error message gets copied into a ticket, a log, a
 * screenshot. Six characters are enough to confirm we are talking about the
 * right project.
 */
function ap_short_project($id)
{
    $id = (string) $id;
    return substr(preg_replace('/[^A-Za-z0-9_-]/', '', $id), 0, 6) . '...';
}

/** Fragment of a doubtful value, made showable in an error message. */
function ap_readable_excerpt($value)
{
    return substr(preg_replace('/[^\x20-\x7E]/', '', (string) $value), 0, 60);
}

/**
 * Canonical origin: scheme://host[:port], scheme and host lowercased, the
 * scheme's default port removed.
 *
 * That is the form the browser puts in the Origin header. The comparison is
 * then a string equality, exact: no prefix, no wildcard, no implicit
 * subdomain. A wildcard on subdomains would look convenient and would open the
 * project to the first page hosted on a subdomain one no longer controls.
 *
 * @return string|null null if this is not an origin
 */
function ap_normalise_origin($origin)
{
    if (!is_string($origin)) {
        return null;
    }
    $origin = trim($origin);
    if ($origin === '' || strlen($origin) > 255) {
        return null;
    }

    $parts = @parse_url($origin);
    if (!is_array($parts) || !isset($parts['scheme'], $parts['host'])) {
        return null;
    }
    // A path, a query string or a fragment means this is not an origin but a
    // URL: we refuse rather than trim in silence, otherwise
    // 'https://example.com/prod' and 'https://example.com/staging' would
    // declare the same thing.
    if (isset($parts['path']) && $parts['path'] !== ''
        || isset($parts['query']) || isset($parts['fragment'])
        || isset($parts['user']) || isset($parts['pass'])) {
        return null;
    }

    $scheme = strtolower($parts['scheme']);
    if ($scheme !== 'http' && $scheme !== 'https') {
        return null;
    }
    $host = strtolower($parts['host']);
    if ($host === '') {
        return null;
    }

    $port = isset($parts['port']) ? (int) $parts['port'] : 0;
    $default = ($scheme === 'https') ? 443 : 80;
    if ($port === 0 || $port === $default) {
        return $scheme . '://' . $host;
    }
    return $scheme . '://' . $host . ':' . $port;
}

/**
 * The origin of the request, normalised, or null if the header is absent.
 *
 * The browser does not write the Origin header on a SAME-ORIGIN request: its
 * absence is therefore not suspicious when self-hosted. It is on a relay, where
 * every legitimate request necessarily comes from elsewhere.
 */
function ap_request_origin()
{
    if (!isset($_SERVER['HTTP_ORIGIN']) || !is_string($_SERVER['HTTP_ORIGIN'])) {
        return null;
    }
    $raw = trim($_SERVER['HTTP_ORIGIN']);
    if ($raw === '' || $raw === 'null') {
        // `null` is what a page with an opaque origin sends (local file,
        // sandbox). It is not a declarable origin: treated as an UNKNOWN
        // origin, not as an absence.
        return 'null';
    }
    $normalised = ap_normalise_origin($raw);
    return $normalised === null ? 'null' : $normalised;
}

/**
 * Applies the domain lock and sets the sharing headers.
 *
 * Three cases, and that is the whole rule (FORMAT.md section 6.2):
 *
 *  - Origin present and RECOGNISED: the response carries
 *    Access-Control-Allow-Origin with the verified origin, never `*`. The
 *    wildcard would make the lock decorative, and it is incompatible anyway
 *    with any move towards credentialed requests.
 *  - Origin present and UNKNOWN: 403, in text/plain. Including for `list` --
 *    which departs from the rule of silence (section 6.4), and deliberately:
 *    silence protects the installation that is not configured yet, not the
 *    site trying to consume somebody else's project.
 *  - Origin ABSENT: allowed when self-hosted (a same-origin request does not
 *    send one). On a relay, every WRITE is refused -- a browser always sends
 *    Origin on a cross-origin request, so a write with no Origin does not come
 *    from a browser.
 *
 * Vary: Origin is set as soon as an intermediate cache could exist: without
 * it, the response allowed for one site would be served to another.
 *
 * @param array  $project the project declaration, already normalised
 * @param bool   $write   does the action change state?
 */
function ap_apply_origin_lock(array $config, $id, array $project, $write)
{
    $origin = ap_request_origin();

    if ($origin === null) {
        if (!ap_is_self_hosted($config) && $write) {
            throw new ApFailure(
                "Write refused: the request carries no Origin header.\n"
                . "On a relay a write necessarily comes from another domain, and a "
                . "browser always attaches that header.\n"
                . "A request with no Origin therefore does not come from a page: it is "
                . "refused.",
                403);
        }
        // Nothing to share: with no Origin there is no origin boundary to
        // cross, and an Access-Control-Allow-Origin would raise the question of
        // what value to put in it.
        return;
    }

    if (!in_array($origin, $project['origins'], true)) {
        // The refused origin is copied into the message: it is the one to
        // compare, character by character, with the line in the configuration
        // file. `http` against `https`, a port, a trailing slash: those are the
        // three mistakes, and none of them shows without the two strings side
        // by side.
        throw new ApFailure(
            "Origin refused for project " . ap_short_project($id) . ".\n"
            . "Origin of the request: " . ap_readable_excerpt($origin) . "\n"
            . "This project does not declare that origin in the server configuration.\n"
            . "This lock is an anti-abuse measure: it stops another site from consuming "
            . "this project id. It is NOT a protection against XSS.",
            403);
    }

    // The headers are handed to errors.php AS WELL, so that a failure crosses
    // the origin boundary. An error the browser hides from the client is a
    // silent failure -- precisely what this tool refuses.
    ap_cors_headers(array(
        'Access-Control-Allow-Origin: ' . $origin,
        'Vary: Origin',
    ));
}

/**
 * The id of the project to attach rows that carry none to, or null if there is
 * no obvious answer.
 *
 * One single situation gives an answer: self-hosted, one single declared
 * project. Those rows are then the notes written by the original tool on that
 * site, and there is nobody else they could belong to.
 *
 * Everywhere else -- a relay, or two declared projects -- we do not guess. A
 * wrong attachment would give one team's notes to another, and nothing in the
 * database would let anyone undo the mistake afterwards: the rows keep no trace
 * of where they came from once the column is filled.
 */
function ap_backfill_project(array $config)
{
    if (!ap_is_self_hosted($config)) {
        return null;
    }
    $projects = ap_declared_projects($config);
    if (count($projects) !== 1) {
        return null;
    }
    $keys = array_keys($projects);
    return $keys[0];
}
