<?php
/**
 * origins.php -- THE DOMAIN LOCK, AND NOTHING ELSE.
 *
 * This file holds two things, and they are better off in the same place
 * because the second depends on the first:
 *
 *   1. WHICH PROJECTS EXIST. The configuration declares them by their id (22
 *      base64url characters, derived from the key IN THE BROWSER: the server
 *      does not compute it, it recognises it).
 *   2. WHICH ORIGINS MAY CONSUME THEM, and the sharing headers that follow.
 *
 * WHAT THIS LOCK IS: an ANTI-ABUSE measure. It stops another site from picking
 * up a project id in the source of a page, writing noise into it and burning
 * the relay's quota.
 *
 * WHAT IT IS NOT, AND IT MUST NEVER BE PRESENTED AS SUCH: a protection against
 * XSS. An XSS runs INSIDE the target page, so with the legitimate origin: it
 * goes through this lock without effort, and it has access to that origin's
 * localStorage anyway, hence to the key. An XSS on an annotated page
 * compromises the notes of the project, full stop. This file changes nothing
 * about that.
 *
 * WHY SEVERAL ORIGINS PER PROJECT. A staging site and the production it
 * becomes are the same project, with the same notes. That is the operational
 * counterpart of the rule "the domain is not in the key" (FORMAT.md section
 * 1.4): if the domain were part of the secret, the day of the production
 * release would be the day every note became unreadable.
 *
 * THE DOMAIN AND THE PATH PREFIX ARE CONFIGURATION, NOT CRYPTOGRAPHY. The path
 * prefix does not appear here at all, in fact: the server does not see paths in
 * encrypted mode, so prefix scope is checked by the client. It is tidiness, not
 * a security boundary (FORMAT.md section 4).
 */

if (!defined('AP_INTERNAL')) {
    http_response_code(404);
    exit;
}

/**
 * The declared projects, checked and normalised. Computed once.
 *
 * A malformed declaration is a configuration FAILURE, not an ignored project: a
 * project one believes declared and which is not returns "no notes" to a team
 * that wrote thirty, and nobody thinks of rereading the local file.
 *
 * @return array key = id, value = array('origins' => [...], 'mode' => '...')
 */
function ap_declared_projects(array $config)
{
    static $memory = null;
    if ($memory !== null) {
        return $memory;
    }

    $raw = isset($config['projects']) && is_array($config['projects'])
        ? $config['projects'] : array();
    // The result is built in a LOCAL variable and handed to the memo only once
    // complete. Without that, a declaration refused halfway through the array
    // would leave behind a half-made list, which the next call would return
    // without a word -- a declared project would become "unknown" through the
    // sole effect of an error in another one.
    $projects = array();

    foreach ($raw as $id => $declaration) {
        $id = (string) $id;
        if (!ap_is_well_formed_id($id)) {
            throw new ApFailure(
                "Invalid configuration: `" . ap_readable_excerpt($id)
                . "` is not a project id.\n"
                . "An id is exactly 22 characters taken from A-Z a-z 0-9 - _ "
                . "(base64url).\n"
                . "It is generated by the setup screen, in the browser, from the key. "
                . "The server does not compute it.",
                500);
        }
        if (!is_array($declaration)) {
            throw new ApFailure(
                "Invalid configuration: project " . ap_short_project($id)
                . " must be declared by an array "
                . "array('origins' => array(...), 'mode' => 'encrypted').",
                500);
        }

        // MODE. `encrypted` by default, and that default is not negotiable on a
        // relay: see below.
        $mode = isset($declaration['mode'])
            ? strtolower(trim((string) $declaration['mode'])) : 'encrypted';
        if ($mode !== 'plain' && $mode !== 'encrypted') {
            throw new ApFailure(
                "Invalid configuration: project " . ap_short_project($id)
                . " declares mode `" . ap_readable_excerpt($mode) . "`.\n"
                . "The only two accepted values are `plain` and `encrypted`.",
                500);
        }
        // Encryption is on by default and can only be switched off when
        // self-hosted, where it protects nothing: the notes are in the same
        // database, on the same machine, behind the same access restriction as
        // the site under review. On a relay there is no access restriction to
        // offer -- plain mode there would make somebody else's notes readable by
        // the relay operator and by whoever finds the id. We refuse WHEN
        // READING THE CONFIGURATION, not at write time: an installation that
        // believes itself protected must learn otherwise at the first
        // diagnostic, not at the first note.
        if ($mode === 'plain' && !ap_allows_plain_mode($config)) {
            throw new ApFailure(
                "Configuration refused: project " . ap_short_project($id)
                . " declares mode `plain` on a `relay` deployment.\n"
                . "Plain mode is only possible when self-hosted, where the notes sit "
                . "behind the same access restriction as the site under review.\n"
                . "On a relay there is nothing of the sort to offer: the notes would be "
                . "readable by the relay operator and by anyone who finds the project id "
                . "in the source of a page.",
                500);
        }

        // ORIGINS.
        $origins = array();
        $declared = isset($declaration['origins']) ? $declaration['origins'] : array();
        if (is_string($declared)) {
            // A single origin written without an array: it is the most likely
            // typo, and refusing it would teach nobody anything.
            $declared = array($declared);
        }
        if (!is_array($declared) || !$declared) {
            throw new ApFailure(
                "Invalid configuration: project " . ap_short_project($id)
                . " declares no origin.\n"
                . "Example: 'origins' => array('https://staging.example.com', "
                . "'https://www.example.com').\n"
                . "A project with no origin is not `open to everyone`: it is unusable, "
                . "and that is intended.",
                500);
        }
        foreach ($declared as $origin) {
            $normalised = ap_normalise_origin($origin);
            /* A PATTERN IS CHECKED WHERE IT IS READ, NOT WHERE IT FAILS TO
               MATCH. A `*` anywhere but in front of the host, or one in front
               of a single label -- `https://*.com`, which is every site on a
               top-level domain -- is refused here, with the configuration,
               rather than accepted and left to answer 403 to everybody. Until
               the pattern existed such a line was accepted without a word and
               matched nothing: no browser ever sends a `*`. */
            if ($normalised !== null && strpos($normalised, '*') !== false) {
                $why = ap_origin_pattern_problem($normalised);
                if ($why !== null) {
                    throw new ApFailure(
                        "Invalid configuration: `" . ap_readable_excerpt((string) $origin)
                        . "` is not an origin pattern.\n" . $why . "\n"
                        . "A pattern is written scheme://*.domain[:port], the star alone "
                        . "in front: https://*.example.com covers every subdomain of "
                        . "example.com, at any depth, and not example.com itself.",
                        500);
                }
            }
            if ($normalised === null) {
                throw new ApFailure(
                    "Invalid configuration: `" . ap_readable_excerpt((string) $origin)
                    . "` is not an origin.\n"
                    . "An origin is written scheme://host[:port], with no path and no "
                    . "trailing slash: https://staging.example.com -- or, for every "
                    . "subdomain at once, https://*.example.com\n"
                    . "That is exactly what the browser puts in the Origin header; "
                    . "anything else will never match.",
                    500);
            }
            $origins[$normalised] = true;
        }

        $projects[$id] = array(
            'origins' => array_keys($origins),
            'mode'    => $mode,
        );
    }

    $memory = $projects;
    return $memory;
}

/** Shape of a project id: 22 base64url characters. */
function ap_is_well_formed_id($id)
{
    return is_string($id)
        && preg_match('/^[A-Za-z0-9_-]{22}$/', $id) === 1;
}

/**
 * The first six characters of an id, for messages.
 *
 * NEVER the whole id: it is what gives access to the project's rows (FORMAT.md
 * section 6.3), and an error message gets copied into a ticket, a log, a
 * screenshot. Six characters are enough to confirm we are talking about the
 * right project.
 */
function ap_short_project($id)
{
    $id = (string) $id;
    return substr(preg_replace('/[^A-Za-z0-9_-]/', '', $id), 0, 6) . '...';
}

/** Fragment of a doubtful value, made showable in an error message. */
function ap_readable_excerpt($value)
{
    return substr(preg_replace('/[^\x20-\x7E]/', '', (string) $value), 0, 60);
}

/**
 * Canonical origin: scheme://host[:port], scheme and host lowercased, the
 * scheme's default port removed.
 *
 * That is the form the browser puts in the Origin header. The comparison is
 * then a string equality, exact -- no prefix, no implicit subdomain -- EXCEPT
 * against a declaration that asks for subdomains in so many words, with a
 * leading `*.`: see ap_origin_allowed().
 *
 * THAT PATTERN WAS REFUSED FOR THREE RELEASES, and the reason is still true:
 * it opens the project to every page on every subdomain, including the one
 * somebody forgot to renew and the one a hosting service hands its customers.
 * It was asked for by the person who runs the servers, for a network where
 * keeping an exhaustive list is the harder problem; so it exists, it has to be
 * written out -- nothing is implied from a bare domain -- and the cost is said
 * wherever it can be typed.
 *
 * @return string|null null if this is not an origin
 */
function ap_normalise_origin($origin)
{
    if (!is_string($origin)) {
        return null;
    }
    $origin = trim($origin);
    if ($origin === '' || strlen($origin) > 255) {
        return null;
    }

    $parts = @parse_url($origin);
    if (!is_array($parts) || !isset($parts['scheme'], $parts['host'])) {
        return null;
    }
    // A path, a query string or a fragment means this is not an origin but a
    // URL: we refuse rather than trim in silence, otherwise
    // 'https://example.com/prod' and 'https://example.com/staging' would
    // declare the same thing.
    if (isset($parts['path']) && $parts['path'] !== ''
        || isset($parts['query']) || isset($parts['fragment'])
        || isset($parts['user']) || isset($parts['pass'])) {
        return null;
    }

    $scheme = strtolower($parts['scheme']);
    if ($scheme !== 'http' && $scheme !== 'https') {
        return null;
    }
    $host = strtolower($parts['host']);
    if ($host === '') {
        return null;
    }

    $port = isset($parts['port']) ? (int) $parts['port'] : 0;
    $default = ($scheme === 'https') ? 443 : 80;
    if ($port === 0 || $port === $default) {
        return $scheme . '://' . $host;
    }
    return $scheme . '://' . $host . ':' . $port;
}

/**
 * The origin of the request, normalised, or null if the header is absent.
 *
 * The browser does not write the Origin header on a SAME-ORIGIN request: its
 * absence is therefore not suspicious when self-hosted. It is on a relay, where
 * every legitimate request necessarily comes from elsewhere.
 */
function ap_request_origin()
{
    if (!isset($_SERVER['HTTP_ORIGIN']) || !is_string($_SERVER['HTTP_ORIGIN'])) {
        return null;
    }
    $raw = trim($_SERVER['HTTP_ORIGIN']);
    if ($raw === '' || $raw === 'null') {
        // `null` is what a page with an opaque origin sends (local file,
        // sandbox). It is not a declarable origin: treated as an UNKNOWN
        // origin, not as an absence.
        return 'null';
    }
    $normalised = ap_normalise_origin($raw);
    /* A REQUEST NEVER CARRIES A PATTERN. No browser writes a `*` in Origin,
       so one that arrives was typed by hand -- and compared as a string it
       would equal the declaration it was copied from, and be let through by
       the rule written for declarations. It is an unknown origin. */
    if ($normalised === null || strpos($normalised, '*') !== false) {
        return 'null';
    }
    return $normalised;
}

/**
 * What is wrong with a declared origin that carries a `*`, or null if it is a
 * well-formed pattern.
 *
 * Well-formed is: the star alone as the first label of the host, followed by
 * at least two labels -- `*.example.com`, not `*.com`, which would be every
 * site on a top-level domain. Nothing here knows which suffixes are public
 * (`*.co.uk` passes, and covers every company in the United Kingdom): that
 * list changes monthly and is not shipped. The line that says so is in
 * FORMAT.md section 6.2, and in the installer beside the field.
 */
function ap_origin_pattern_problem($origin)
{
    if (!preg_match('#^(https?)://\*\.([^/*]+)$#', $origin, $m)) {
        return 'The star must stand alone in front of the host, and nowhere else.';
    }
    $host = preg_replace('#:\d+$#', '', $m[2]);
    if (strpos($host, '.') === false) {
        return 'A star in front of a single label covers every site on a top-level '
            . 'domain.';
    }
    if (!preg_match('#^[a-z0-9_-]+(\.[a-z0-9_-]+)+$#', $host)) {
        return 'What follows the star is not a domain.';
    }
    return null;
}

/**
 * Is this request origin one of the declared ones?
 *
 * Exact equality first, which is every declaration but the patterns. A
 * pattern `scheme://*.base[:port]` then matches an origin with the same scheme
 * whose `host[:port]` ends in `.base[:port]` -- so the port has to be the same
 * too, since both sides are canonical, and `base` itself is NOT matched: the
 * star stands for at least one label. `https://evil-example.com` does not end
 * in `.example.com`, which is why the dot is part of what is compared.
 *
 * @param string $origin   the request's, from ap_request_origin() -- never a
 *                         pattern, see there
 * @param array  $declared the project's, normalised
 */
function ap_origin_allowed($origin, array $declared)
{
    if (in_array($origin, $declared, true)) {
        return true;
    }
    $cut = strpos($origin, '://');
    if ($cut === false) {
        return false;
    }
    $scheme = substr($origin, 0, $cut);
    $rest   = substr($origin, $cut + 3);
    foreach ($declared as $pattern) {
        $star = strpos($pattern, '://*.');
        if ($star === false || substr($pattern, 0, $star) !== $scheme) {
            continue;
        }
        $suffix = '.' . substr($pattern, $star + 5);
        if (strlen($rest) > strlen($suffix)
            && substr($rest, -strlen($suffix)) === $suffix) {
            return true;
        }
    }
    return false;
}

/**
 * Applies the domain lock and sets the sharing headers.
 *
 * Three cases, and that is the whole rule (FORMAT.md section 6.2):
 *
 *  - Origin present and RECOGNISED: the response carries
 *    Access-Control-Allow-Origin with the verified origin, never `*`. The
 *    wildcard would make the lock decorative, and it is incompatible anyway
 *    with any move towards credentialed requests.
 *  - Origin present and UNKNOWN: 403, in text/plain. Including for `list` --
 *    which departs from the rule of silence (section 6.4), and deliberately:
 *    silence protects the installation that is not configured yet, not the
 *    site trying to consume somebody else's project.
 *  - Origin ABSENT: allowed when self-hosted (a same-origin request does not
 *    send one). On a relay, every WRITE is refused -- a browser always sends
 *    Origin on a cross-origin request, so a write with no Origin does not come
 *    from a browser.
 *
 * Vary: Origin is set as soon as an intermediate cache could exist: without
 * it, the response allowed for one site would be served to another.
 *
 * @param array  $project the project declaration, already normalised
 * @param bool   $write   does the action change state?
 */
function ap_apply_origin_lock(array $config, $id, array $project, $write)
{
    $origin = ap_request_origin();

    if ($origin === null) {
        if (ap_requires_origin_on_writes($config) && $write) {
            throw new ApFailure(
                "Write refused: the request carries no Origin header.\n"
                . "This server requires one on a write, which is what "
                . "`require_origin_on_writes` says: a write reaching it comes from "
                . "another domain, and a browser always attaches that header.\n"
                . "A request with no Origin therefore does not come from a page: it is "
                . "refused.",
                403);
        }
        // Nothing to share: with no Origin there is no origin boundary to
        // cross, and an Access-Control-Allow-Origin would raise the question of
        // what value to put in it.
        return;
    }

    // A project admitted by open registration declares no origin, and cannot:
    // see `open_registration` in config.php. The header is still required on a
    // write -- that check is above, and it is what keeps a write coming from
    // something other than a page out. What is dropped here, deliberately, is
    // the comparison against a list that does not exist.
    if ($project['origins'] === null) {
        ap_cors_headers(array(
            'Access-Control-Allow-Origin: ' . $origin,
            'Vary: Origin',
        ));
        return;
    }

    if (!ap_origin_allowed($origin, $project['origins'])) {
        // The refused origin is copied into the message: it is the one to
        // compare, character by character, with the line in the configuration
        // file. `http` against `https`, a port, a trailing slash: those are the
        // three mistakes, and none of them shows without the two strings side
        // by side.
        throw new ApFailure(
            "Origin refused for project " . ap_short_project($id) . ".\n"
            . "Origin of the request: " . ap_readable_excerpt($origin) . "\n"
            . "This project does not declare that origin in the server configuration.\n"
            . "This lock is an anti-abuse measure: it stops another site from consuming "
            . "this project id. It is NOT a protection against XSS.",
            403);
    }

    // The headers are handed to errors.php AS WELL, so that a failure crosses
    // the origin boundary. An error the browser hides from the client is a
    // silent failure -- precisely what this tool refuses.
    ap_cors_headers(array(
        'Access-Control-Allow-Origin: ' . $origin,
        'Vary: Origin',
    ));
}

/**
 * The id of the project to attach rows that carry none to, or null if there is
 * no obvious answer.
 *
 * One single situation gives an answer: self-hosted, one single declared
 * project. Those rows are then the notes written by the original tool on that
 * site, and there is nobody else they could belong to.
 *
 * Everywhere else -- a relay, or two declared projects -- we do not guess. A
 * wrong attachment would give one team's notes to another, and nothing in the
 * database would let anyone undo the mistake afterwards: the rows keep no trace
 * of where they came from once the column is filled.
 */
function ap_backfill_project(array $config)
{
    /* The rows of a 1.2.0 database are attached only where the notes belong to
       the site that serves them -- the same condition that lets a project keep
       its words readable. Attaching them anywhere else could give one team's
       notes to another, and nothing in the database would let anyone undo it. */
    if (!ap_allows_plain_mode($config)) {
        return null;
    }
    $projects = ap_declared_projects($config);
    if (count($projects) !== 1) {
        return null;
    }
    $keys = array_keys($projects);
    return $keys[0];
}
